name: Daily Payment Reminder

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9 AM UTC (Change if needed)

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Reminder Script
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: node functions/reminder.js
